version: '3'
services:
        app:
                build:
                        context: .
                        dockerfile: .docker/Dockerfile
                image: updown-server
                ports:
                        - 8090:80
