version: '3'
services:
        app:
                build:
                        context: .
                        dockerfile: .docker/Dockerfile
                image: updown-server
                restart: always
                volumes:
                        - files:/srv/app/storage/app/files
                ports:
                        - 8090:80

volumes:
        files:
                external: false
